# Generated by Django 5.2.18 on 2026-10-07 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stage',
            field=models.CharField(choices=[('LEAD', 'Lead (New)'), ('CONTACTED', 'Contacted'), ('NEGOTIATING', 'Negotiating'), ('ACTIVE', 'Active Account'), ('INACTIVE', 'Inactive')], default='LEAD', max_length=20),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Phone Call'), ('MEETING', 'Meeting'), ('NOTE', 'Internal Note')], default='NOTE', max_length=15)),
                ('notes', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='erp.account')),
            ],
        ),
    ]
