# Generated by Django 5.2.18 on 2026-10-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=100, null=True, verbose_name='PARTY')),
                ('rf_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='RF. NO')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='INVOICE NO')),
                ('master_invoice_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='MASTER INVOICE NO')),
                ('item', models.CharField(blank=True, max_length=500, null=True, verbose_name='ITEM')),
                ('order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ORDER NO.')),
                ('purchase_order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='PURCHASE ORDER NO.')),
                ('sale_ch_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='SALE CH. NO.')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='VALUE')),
            ],
        ),
    ]
