# Generated by Django 5.2.18 on 2026-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_salerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_late', models.CharField(blank=True, max_length=100, null=True, verbose_name='NO OF LATE')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='REMARKS')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref# ID')),
                ('portals', models.CharField(blank=True, max_length=100, null=True, verbose_name='Portals')),
                ('order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order No.')),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer Name')),
                ('picture', models.CharField(blank=True, max_length=500, null=True, verbose_name='Picture')),
                ('order_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Date')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='COTTON/JUTE')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='SIZE')),
                ('tassel_fringes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tassel/Fringes')),
                ('expected_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Expected date')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('hold_cancelled_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='HOLD/ CANCELLED DATE')),
                ('dispatch_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispatch Date')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('photos', models.CharField(blank=True, max_length=500, null=True, verbose_name='Photos')),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Date')),
                ('complete_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complete Name')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='street')),
                ('street2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('company_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Type')),
                ('gst_treatment', models.CharField(blank=True, max_length=100, null=True, verbose_name='GST Treatment')),
                ('products', models.TextField(blank=True, null=True, verbose_name='PRODUCTS')),
                ('size_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size 2')),
                ('pcs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pcs.')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('column_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Column 2')),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='HSN CODE')),
                ('dtp_payment_received', models.CharField(blank=True, max_length=100, null=True, verbose_name='DTP PAYMENT RECEIVED')),
                ('check_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='CHECK BY')),
                ('shipping_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='SHIPPING DATE')),
                ('status_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='STATUS 2')),
                ('est_date_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='EST DATE 1')),
                ('est_date_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='EST DATE 2')),
                ('rcvd_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rcvd. Date')),
                ('rcvd_paper_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rcvd. Paper date')),
                ('send_paper_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='SEND PAPER DATE')),
            ],
        ),
    ]
