# Generated by Django 5.2.18 on 2026-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_masterorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='sale_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VALUE'),
        ),
    ]
