# Generated by Django 5.2.18 on 2026-10-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_salerecord_sale_date_alter_salerecord_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Debit Note No')),
                ('party_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Party Name')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Grand Total')),
                ('rupees_words', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rupees in Words')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(default=1, verbose_name='Sr No')),
                ('particulars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Particulars')),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill No')),
                ('bill_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill Date')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Debit Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.debitnote')),
            ],
        ),
    ]
