# Generated by Django 5.2.18 on 2026-10-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_debitnote_debitnoteitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website Organic"),
                            ("ADS", "Paid Ads"),
                            ("SOCIAL", "Social Media"),
                            ("REFERRAL", "Referral"),
                            ("COLD_CALL", "Cold Call"),
                            ("OTHER", "Other"),
                        ],
                        default="WEBSITE",
                        max_length=50,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("LOST", "Lost"),
                            ("CONVERTED", "Converted to Account"),
                        ],
                        default="NEW",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
